### ISSUE TITLE
Syntax Highlight Fails

### ISSUE THREAD

**Issue by Swivelgames** [HHogg/remarkable-react#1]
After switching over to using `remarkable-react`, I'm no longer able to take advantage of `hljs`.

```
const md = new Remarkable({
	highlight: function (str, lang) {
		if (lang && HighlightJS.getLanguage(lang)) {
			try {
				return HighlightJS.highlight(lang, str).value;
			} catch (err) {}
		}

		try {
			return HighlightJS.highlightAuto(str).value;
		} catch (err) {}

		return '';
	}
});
```

This is my current code, which I know will not work because `remarkable-react` replaces the renderer. Unfortunately this renders most all of the plugins useless...

**Comment by Swivelgames** [comment]
I think a unique solution for this would be to modify the `code` component to pass in the language as a prop. This would enable the following syntax:

```javascript
...
code: (props) => (
    <code className={'language-'+props.language}>
        {props.children}
    </code>
),
...
```

**Comment by HHogg** [comment]
Hey @Swivelgames thanks for trying this out. Highlighting was something I still needed to test, now I know it definitely doesn't work I'll take a look!

**Comment by Swivelgames** [comment]
@HHogg Thanks Harry! 😄

**Comment by HHogg** [comment]
So to keep this renderer impartial to syntax highlighting libraries #4 provides an example of how to handle highlighting with HighlightJS.
