### ISSUE TITLE
Attribute "target" does not work

### ISSUE THREAD

**Issue by edbond88** [HHogg/remarkable-react#10]
Hi! Attribute "target" for links does not render

```js
const md = new Remarkable({
  typographer: false,
  linkTarget: '_blank',
  linkify: true,
})

md.block.ruler.disable(['table', 'footnote', 'deflist'])

md.renderer = new RemarkableReactRenderer()
```

Without `md.renderer = new RemarkableReactRenderer()` its work fine

**Comment by HHogg** [comment]
Thanks for logging this @edbond88. Hopefully this has been resolved by #11

**Comment by HHogg** [comment]
This is now available under [v1.0.1](https://github.com/HHogg/remarkable-react/releases/tag/v1.0.1)... Let me know if it works as you expect :)

**Comment by edbond88** [comment]
Thanks! Now its work fine!

**Comment by HHogg** [comment]
Great thanks for letting me know :)
