### ISSUE TITLE
Custom components doesn't get children

### ISSUE THREAD

**Issue by charliesbox** [HHogg/remarkable-react#13]
I was following the same example found in the tests for custom components:
https://github.com/HHogg/remarkable-react/blob/master/test/utils.js#L11

However, when I checked the props, the children value is always undefined.

So, for this test case https://github.com/HHogg/remarkable-react/blob/master/test/renderer.test.js#L947
it will call the custom component, without the children value.

If I add the state.src to a different property, like `hLevel: state.src`, I will get the value I need, but it is a weird hack.

**Comment by charliesbox** [comment]
Oh, I got something

https://github.com/HHogg/remarkable-react/blob/master/src/token-tree-builder.js#L34

So, by doing this
```
    state.push({
      type: "video_token",
      content: state.src,
    });
```
it works, cause it is looking for the content property to move that value into the children.

Is this expected?

**Comment by HHogg** [comment]
As for _this_ library's part of the rendering, if a custom component is given to the config to map to a "`video_token`", then it's props should include any data that is given to the token when it was parsed.

**Comment by charliesbox** [comment]
thanks for the response @HHogg. My concern is related to an example that I found to "read" a mention

https://github.com/debiki/debiki-server-old/blob/ec0ca6743233b4b09d7fa8ba4e91803082749b65/client/app/editor/mentions-remarkable-plugin.js

Here, it uses an inline ruler, and they can add other values to the state (in this case, a custom username)

If I try to do the same, I can't receive that custom value. So I relate that with missing props, like children.

Am I missing something? Thanks for your help.

**Comment by HHogg** [comment]
Looking at the plugin, I can't see any reason why it wouldn't come through. @charliesbox would you mind posting your config here?

**Comment by HHogg** [comment]
I think this was also due to the same issue reported in #20 which is now resolved.
