### ISSUE TITLE
How to use with html?

### ISSUE THREAD

**Issue by evgenyrodionov** [HHogg/remarkable-react#15]
When I'm trying use with `html: true` as
```js
const remarkable = new Remarkable({ html: true, typographer: true });
```

I got this on `remarkable.render(md)`:

![image](https://user-images.githubusercontent.com/775692/36592714-f9fae710-18a7-11e8-8d97-f190973bd743.png)

Without `html: true` I got:

![image](https://user-images.githubusercontent.com/775692/36592758-1c1e49cc-18a8-11e8-9ffd-cc25852bbb3a.png)

On both variants result is
![image](https://user-images.githubusercontent.com/775692/36592727-04b4ee1c-18a8-11e8-9128-97f563b73936.png)

**Comment by evgenyrodionov** [comment]
It also not works with `<p>` tags or `<aside>`

![image](https://user-images.githubusercontent.com/775692/36593919-fab32dca-18ac-11e8-9249-86fabb9011b8.png)

**Comment by evgenyrodionov** [comment]
@HHogg ?

**Comment by HHogg** [comment]
Hey @evgenyrodionov, I'm looking at how best to handle HTML now. 

I guess because how React handles inserting html (`dangerouslySetInnerHTML`) I suspect there will be a comprise on a "container element" for the html to be inserted in. Will keep this issue updated.

**Comment by HHogg** [comment]
@evgenyrodionov should be fixed by #16.

**Comment by HHogg** [comment]
@evgenyrodionov Please let me know if this indeed does fix your issue.

**Comment by evgenyrodionov** [comment]
Everything is fine, thanks
