### ISSUE TITLE
Footnotes support

### ISSUE THREAD

**Issue by lukaleli** [HHogg/remarkable-react#17]
Hey, @HHogg !

First of all: great library!

I'm planning to use this library in my project and I'm fiddling around with it for a couple of hours now. I need to support footnotes. I can see that these are not added yet in the library. Can you share what are the challenges regarding footnotes implementation?
I'm trying to wrap my head around `remarkable` parsing and tokenization approach and your library and perhaps implement it by my own by adding custom component. I just wanted to know beforehand what are the challenges with footnotes or whether you're planning to release a new library version with support for these.

Thanks in advance!

**Comment by HHogg** [comment]
Hey @lukaleli, there was no technical reason at the time for not doing it, it was just not something I needed at the time. I also haven't looked into it yet, but I suspect it will need a little bit of custom behaviour for it as it needs to push the components to render to the end. 

Quite an interesting one, so I'm interested in having a look. I'll try to find some time later one evening this week.

**Comment by lukaleli** [comment]
Would be great to see that working :) Thanks and looking forward to that!

**Comment by HHogg** [comment]
@lukaleli This should now be available to you under version v1.3.0, please let me know if it's all ok!

**Comment by lukaleli** [comment]
Great news! Will test it when I’m back from vacation. Thanks a lot!
