### ISSUE TITLE
Extend markdown

### ISSUE THREAD

**Issue by azizpunjani** [HHogg/remarkable-react#2]
Thank you for creating this great React renderer for the remarkable repo. I'd love to use this in a project I am working on. I did have a few questions. I've poked around the codebase somewhat but wasn't able to figure this out. Would I be able to add custom rules to extend markdown? I'd like to write my own rule that will be added to the parser, how would I be able to render that as a react component and pass it the required props? 

I just need some guidance, I can probably figure it out from there. Thank you in advance.

**Comment by HHogg** [comment]
Hey @azizpunjani 👋 the actual parsing of the markdown is down by the awesome [remarkable](https://github.com/jonschlinkert/remarkable) library. Which AFAIK is setup to extend/enable/disable rules and add plugins, so that is where you could add your own markdown rules to. 

The way this library works is to look at the tokens that remarkable outputs and looks for a matching react component for the `token.type`. So you could then set up `remarkable-react` like ...

```js
new RemarkableReactRenderer({
  components: {
    customRemarkableTokenType: CustomReactComponent,
  },
});
```

**Comment by azizpunjani** [comment]
@HHogg Thanks for your reply. I also had to add the custom token type to https://github.com/HHogg/remarkable-react/blob/master/src/lib/token-types.js so it would be able to custom render the react component. Does this sound right? I couldn't find a way to configure the addition of other token types.

**Comment by HHogg** [comment]
@azizpunjani Yes you're right. I've made some changes, which will allow you to pass in options for custom tokens. It will look like this....

```js
// Example remarkable setup 
remarkable.inline.ruler.push('custom_rule', customRule);

// Example remarkable-react setup 
new RemarkableReactRenderer({
  components: {
    custom_component: CustomComponent,
  },
  tokens: {
    custom_token: 'custom_component',
  },
});
```

Do you think this is a good approach and will work for you?

**Comment by azizpunjani** [comment]
@HHogg that looks good! I believe that should work for me. Thanks for looking into this.

**Comment by HHogg** [comment]
Great, I'm just going to quickly set up [`semantic-release`](https://github.com/semantic-release/semantic-release) and then I'll merge PR #3, which will make this available.

**Comment by HHogg** [comment]
Sorry for the delay. This has now been released under `v.0.1.0`

**Comment by azizpunjani** [comment]
@HHogg thanks!
