### ISSUE TITLE
TokenTree is not extendable

### ISSUE THREAD

**Issue by DxCx** [HHogg/remarkable-react#21]
Hey,

TokenTree is not exported anywere, which means i cannot extend it and make my own implementation,
can it be exported please?

**Comment by HHogg** [comment]
Hey @DxCx, yeah exporting it is not a problem. What part of the TokenTree are you after? 

At the moment, the TokenTree is kind of tied to resolving token/props/components (which is configurable through the renderer API). If you're just after the part of transforming the `remarkable` token array into a tree structure, then it might be better if I expose this as a util function instead (so it doesn't come with all the other bits).

**Comment by DxCx** [comment]
This is exactly it,
I am building a diff token type out of marked input
So im calling my function if its the marked one or super (yours) if its not :)

**Comment by DxCx** [comment]
ping @HHogg ?

**Comment by DxCx** [comment]
Thank you!

**Comment by HHogg** [comment]
@DxCx [v1.4.0](https://github.com/HHogg/remarkable-react/releases/tag/v1.4.0) now has the TokenTree exported. Give a shout here if there's any issues.

**Comment by DxCx** [comment]
alright! thanks alot :dancer:
