### ISSUE TITLE
Custom Component with Custom Token example

### ISSUE THREAD

**Issue by Rall3n** [HHogg/remarkable-react#22]
Is there an detailed example for the usage of a custom component with a custom token? Definition inside the `components` and `tokens` options and usage inside Markdown.

**Comment by HHogg** [comment]
@Rall3n I think [Remarkable](https://github.com/jonschlinkert/remarkable) have got some good documentation on the custom token part (as it's their feature) from this library's perspective you simply map the token you named in the Remarkable config to a custom component name in the renderers config and your react component will then get all of the properties that your token would get. 

Issue #6 may have a bit extra reading that will help you out.

**Comment by Rall3n** [comment]
Thanks to the issue and the links you provided inside of it I finally managed to write a working custom Markdown tag.

**Comment by HHogg** [comment]
Sweet, I'll add a bit of similar information to the README.md to help others in future.
