### ISSUE TITLE
br not parsed

### ISSUE THREAD

**Issue by GautierT** [HHogg/remarkable-react#5]
Hi, 
i can make html parsed. 
i'm doing like that but the <br /> are still write as plain text and are not parsed.
```
const Remarkable = require('remarkable')
const RemarkableReactRenderer = require('remarkable-react')

const md = new Remarkable({
  html: true,
  breaks: false
})
md.renderer = new RemarkableReactRenderer({
  html : true,
  breaks : false,
  components: {
    'table': (props) => <Table {...props} celled/>,
  }
})
```

Awesome package, thanks !

**Comment by HHogg** [comment]
Hey @GautierT, so the `html_block` token is an interesting one. From a basic rendering perspective, it's as simple as returning the content from the token, as [shown here in the default renderer](https://github.com/jonschlinkert/remarkable/blob/master/lib/rules.js#L314). But bring this into the world of react components, there are some compromises to make. 

One simple way to accomplish it is by creating a component that renders a superfluous element to insert the html into.... something like  

```jsx
render() {
  return (
    <div dangerouslySetInnerHTML={ { __html: this.props.content } } />
  );
}
```

We could allow the element type to be configured but it still adds an unintended element into the output, which isn't ideal. 

Maybe a better way to handle this is to infer the react element from the first element of the HTML input and then exclude that from the `dangerouslySetInnerHTML` input. 

I'll have a go at the latter approach first and see how stable it seems.

**Comment by GautierT** [comment]
Hi @HHogg,
As i'm re-reading my question i see some error in it. 
I wanted to say that the HTML i put in my markdown are not parsed. 
With this input : 
```
## Hello

Some Text ! 

<br />

Hello
```

I have this output : 

> # Hello
> Some Text ! 
> `<br />`
> Hello

Why the `<br />` is not parsed ?

The `html` parameter set to `true` seems to do nothing.

I dont really understand your answer.
Should i display my output with `<div dangerouslySetInnerHTML={ { __html: md.render(item.content) } } />` instead of just `<div>{md.render(item.content)}</div>` ?

Thanks for taking the time !

**Comment by HHogg** [comment]
So Remarkable handles the parsing of the markdown, this library handles the rendering. Remarkable passes objects called tokens that contain the information, this library simply maps those tokens to react components. 

Setting `html` to true in the remarkable config simply tells remarkable to identify and parse html... this library currently doesn't handle the rendering part of it as it's not core markdown behaviour. 

The complications come from react requiring a top level component to insert the raw HTML into. I don't think it's difficult to handle 😅 looking at it now.

**Comment by GautierT** [comment]
Okay !  If you find a solution so that `<br />` are parsed thanks a lot !

**Comment by GautierT** [comment]
@HHogg : Hi again !
Have you found a solution ? I want to put <a><a/> in my markdown (to use http://docs.embed.ly/v1.0/docs/platformjs) but the <a></a> are not transform to classic HTML and displayed as text.

**Comment by HHogg** [comment]
Hi @GautierT sorry for the delay with this. I have investigated it, this being a React renderer has an issue with how to handle the raw HTML, especially invalid HTML. In terms of the `<br />` passing, do you think your issue might be resolved by #7 ?

To handle general raw HTML... I'm thinking the most reliable way is to have an option to specify an additional element type to put the contents into ... this isn't ideal as it won't reflect what remarkables renderer would output, but this is a constraint of React itself.

**Comment by knubie** [comment]
#16 handles `htmlblock`, but not `htmltag`, which is used in inline tokens. `<br/>` belongs to the `htmltag` category.

For example:
```md
Some inline <span>html</span> text.
```
Will yield:
```
[
  {type: "paragraph_open", ...}
  {type: "inline", content: "Some inline <span>html</span> text.",
   children: [
     {type: "text", content: "Some inline "},
     {type: "htmltag", content: "<span>"},
     {type: "text", content: "html"},
     {type: "htmltag", content: "</span>"},
     {type: "text", content: " text."},
   ]
  }
]
```

Handling inline html is a bit trickier I think, because there's no distinction between opening and closing tags.

**Comment by HHogg** [comment]
Interesting, thanks @knubie. I'm intending to revisit this library and give it a bit of an update. I'll keep this problem in mind when I do and try to get this working too.

**Comment by HHogg** [comment]
@knubie I've opened up a new issue (#24) to track this.
