### ISSUE TITLE
Custom Token / Custom Component interaction is unclear

### ISSUE THREAD

**Issue by greeze** [HHogg/remarkable-react#6]
How do custom tokens and custom components interact? How are custom tokens expressed in Markdown?

The documentation isn't clear about how these things work together, or about how the Markdown should look after these settings are defined in the configuration.

How can I use Markdown to render `MyCustomComponent`?

What I'm doing:
```javascript
const rm = new Remarkable({ html: true })
rm.renderer = new RemarkableReactRenderer({
  components: {
    example1: (props) => { return <MyCustomComponent ...props /> }
  },
  tokens: {
    example1_token: 'example1'
  }
})
rm.render('example1')
```

The result is the text "example1" instead of `MyCustomComponent`. What's up?

**Comment by HHogg** [comment]
Hi @greeze 👋 so the custom tokens is actually a feature of [remarkable](https://github.com/jonschlinkert/remarkable), this library simply handles the rendering part. 

It would probably be better to check out remarkable's documentation around this as it probably explains it a bit clearer but AFAIK it works something like this ... 

#### Define your custom parser function and register it with remarkable

```js
remarkable.inline.ruler.push('video_rule', (state, silent) => {
  // Where '%' is your markdown identifier 
  if (state.src[state.pos] !== '%') return false;

  if (!silent) {
    state.push({
      type: 'video_token',
      text: state.src,
      level: state.level,
    })
  }

  state.pos += state.src.length;

  return true
});
```

Then your markdown would look something like ... 

```md
% Video source 
```

Remarkable will then give this renderers a token with the parsed information, and should work exactly as you have it defined above. 

Let me know if this helps or not.

**Comment by HHogg** [comment]
Some useful additional reading: 
* [Official extending markdown syntax docs](https://github.com/jonschlinkert/remarkable/blob/master/docs/plugins.md#extending-remarkable-and-the-markdown-syntax)
* [Remarkable issue around this](https://github.com/jonschlinkert/remarkable/issues/48)

**Comment by greeze** [comment]
That was _exactly_ what I needed, thank you! I'll post back with some code in a bit to hopefully clarify this a little for future head-scratchers.

**Comment by HHogg** [comment]
Awesome :) let me know if you have any suggestions to improve the docs around it.

**Comment by greeze** [comment]
Our needs for custom tokens/components were pretty basic (no dynamic props or children), so I wrote a utility to make it easier for us. The full code for the utility is at the end of this comment. The usage looks like this:

**MyComponent.jsx**
Here we set up our custom tokens `{{fancy_large}}` and `{{fancy_small}}`. When we use them in our markdown, they will be replaced with actual React components:
```jsx
import FancyComponent from 'components/FancyComponent.jsx'
import renderMarkdown from 'utils/renderMarkdown.js'
import markdownSource from './MyComponent.md'

const renderedMarkdown = renderMarkdown(markdownSource, {
  '{{fancy_large}}': () => <FancyComponent size="large">I'm large!</FancyComponent>,
  '{{fancy_small}}': () => <FancyComponent size="small">I'm small!</FancyComponent>
})

class MyComponent extends React.Component {
  render() {
    return <div>{renderedMarkdown}</div>
  }
}

export default MyComponent
```

**MyComponent.md**
Here's our markdown. Our custom tokens `{{fancy_large}}` and `{{fancy_small}}` will be replaced with the actual components when this is rendered.
```markdown
### Check out my fancy components!
* Here's my large fancy component: {{fancy_large}}
* Here's my small fancy component: {{fancy_small}}
```

**utils/renderMarkdown.js**
This is the utility that abstracts away the registration of custom tokens and the actual rendering of the markdown.
```jsx
import React from 'react'
import Remarkable from 'remarkable'
import RemarkableReactRenderer from 'remarkable-react'

/**
 * Registers a custom token to be parsed by Remarkable,
 * then handed off to Remarkable-React for rendering:
 * https://github.com/HHogg/remarkable-react/issues/6
 */
const addCustomMarkdownToken = (remarkable, tag) => {
  if (!remarkable || !tag || typeof tag !== 'string') return
  remarkable.inline.ruler.push(tag, (state, silent) => {
    if (state.src.substr(state.pos, tag.length) !== tag) return false
    if (!silent) {
      state.push({ type: tag, text: state.src, level: state.level })
    }
    state.pos += tag.length
    return true
  })
}

const addCustomMarkdownTokens = (remarkable, tags) => {
  if (!remarkable || !tags || !tags.length) return
  if (typeof tags === 'string') {
    addCustomMarkdownToken(remarkable, tags)
  } else if (Array.isArray(tags)) {
    tags.forEach((tag) => {
      addCustomMarkdownToken(remarkable, tag)
    })
  }
}

/**
 * Parses a customComponents object that contains tokens as keys,
 * and custom React components as values.
 * For example:
 * {
 *   '%example1%': () => (<MyComponent>Example 1</MyComponent>),
 *   '%example2%': () => (<MyOtherComponent>Example 2</MyOtherComponent>)
 * }
 * Automatically registers the tokens with Remarkable so that they can be parsed
 * and rendered into their associated components.
 */
const createTokensFromCustomComponents = (remarkable, customComponents) => {
  if (!remarkable || !customComponents) return {}
  const tokens = Object.keys(customComponents)
  addCustomMarkdownTokens(remarkable, tokens)
  const customTokens = {}
  tokens.forEach((token) => { customTokens[token] = token })
  return customTokens
}

const defaultCustomComponents = {
  // replace '<p>' with '<div>' to prevent React nesting warnings
  p: ({ children }) => <div className="p">{children}</div>
}

export default (markdownSource, customComponents = {}) => {
  const rm = new Remarkable()
  const customTokens = createTokensFromCustomComponents(rm, customComponents)
  rm.renderer = new RemarkableReactRenderer({
    components: { ...defaultCustomComponents, ...customComponents },
    tokens: { ...customTokens }
  })
  return rm.render(markdownSource)
}
```

**Comment by HHogg** [comment]
That's really interesting to see and will likely help future visitors to this thread :) thanks for sharing @greeze
